=== Georgitanev/python38_proj_adata/src/parliamentbg/parliamentbg/spiders/json_schema_with_email.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"name": {"type": "string"}, "date_born": {"type": "string"}, "place_born": {"anyOf": [{"type": "null"}, {"type": "string"}]}, "profession": {"anyOf": [{"type": "null"}, {"type": "string"}]}, "lang": {"anyOf": [{"type": "null"}, {"type": "string"}]}, "party": {"type": "string"}, "email": {"title": "Email address", "type": "string", "pattern": "^\\S+@\\S+\\.\\S+$", "format": "email", "minLength": 6, "maxLength": 127}, "url": {"type": "string"}, "education": {"anyOf": [{"type": "null"}, {"type": "string"}]}, "pp": {"type": "string"}, "dob": {"type": "string"}}, "required": ["date_born", "dob", "education", "email", "lang", "name", "party", "place_born", "pp", "profession", "url"], "title": "Welcome"}

=== Georgitanev/python38_proj_adata/src/parliamentbg/test_db.json
[
{"name": "ИВА МИТЕВА ЙОРДАНОВА-РУПЧЕВА", "date_born": "1972-10-25", "place_born": "Разград България", "profession": "юрист;", "lang": "английски;", "party": "ПП ИМА ТАКЪВ НАРОД", "email": "Predsedatel@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3013", "education": null, "pp": "ITN", "dob": "19721025"},
{"name": "ВАЛЕНТИНА ВАСИЛЕВА ВАСИЛЕВА-ФИЛАДЕЛФЕВС", "date_born": "1975-05-09", "place_born": "Сливен България", "profession": "преподавател;пианист;", "lang": "английски;руски;", "party": "ИЗПРАВИ СЕ! МУТРИ ВЪН!", "email": "Valentina.Vasileva@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3032", "education": null, "pp": "IMV", "dob": "19750509"},
{"name": "ВАЛЕНТИН МИРЧОВ МИЛУШЕВ", "date_born": "1966-03-15", "place_born": "Самоков България", "profession": null, "lang": null, "party": "ГЕРБ-СДС", "email": "Valentin.Milushev@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3045", "education": null, "pp": "GERP", "dob": "19660315"},
{"name": "БЮРХАН ИЛИЯЗОВ АБАЗОВ", "date_born": "1965-06-17", "place_born": "с. Смирненски България", "profession": null, "lang": null, "party": "Движение за права и свободи - ДПС", "email": "Byurhan.Abazov@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3219", "education": null, "pp": "DPS", "dob": "19650617"},
{"name": "БОРИСЛАВ ДИМИТРОВ САНДОВ", "date_born": "1982-12-16", "place_born": null, "profession": null, "lang": null, "party": "ДЕМОКРАТИЧНА БЪЛГАРИЯ – ОБЕДИНЕНИЕ (ДА България, ДСБ, Зелено движение)", "email": "Borislav.Sandov@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3031", "education": null, "pp": "DB", "dob": "19821216"},
{"name": "БОРИСЛАВ ГУЦАНОВ ГУЦАНОВ", "date_born": "1967-06-17", "place_born": "Варна България", "profession": null, "lang": null, "party": "БСП за БЪЛГАРИЯ", "email": "Borislav.Gutsanov@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3107", "education": null, "pp": "BSP", "dob": "19670617"},
{"name": "БОРИС ЦВЕТКОВ ЦВЕТКОВ", "date_born": "1973-11-25", "place_born": "София България", "profession": null, "lang": null, "party": "БСП за БЪЛГАРИЯ", "email": "Boris.Tsvetkov@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3016", "education": null, "pp": "BSP", "dob": "19731125"},
{"name": "БОНКА СЕРГЕЕВА ВАСИЛЕВА", "date_born": "1979-04-07", "place_born": null, "profession": null, "lang": null, "party": "ДЕМОКРАТИЧНА БЪЛГАРИЯ – ОБЕДИНЕНИЕ (ДА България, ДСБ, Зелено движение)", "email": "Bonka.Vasileva@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3029", "education": null, "pp": "DB", "dob": "19790407"},
{"name": "БОЙКО ПЕТРОВ КАФЕДЖИЕВ", "date_born": "1980-03-30", "place_born": "София България", "profession": "предприемач;", "lang": null, "party": "ПП ИМА ТАКЪВ НАРОД", "email": "Boyko.Kafedzhiev@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3121", "education": null, "pp": "ITN", "dob": "19800330"},
{"name": "БОГДАН ЕМИЛОВ БОЦЕВ", "date_born": "1980-04-30", "place_born": "София България", "profession": null, "lang": null, "party": "БСП за БЪЛГАРИЯ", "email": "Bogdan.Botsev@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3083", "education": null, "pp": "BSP", "dob": "19800430"},
{"name": "БЛАГОВЕСТ КИРИЛОВ КИРИЛОВ", "date_born": "1986-10-12", "place_born": null, "profession": null, "lang": null, "party": "БСП за БЪЛГАРИЯ", "email": "Blagovest.Kirilov@parliament.bg", "url": "https://www.parliament.bg/bg/MP/2998", "education": null, "pp": "BSP", "dob": "19861012"},
{"name": "БАЙРАМ ЮЗКАН БАЙРАМ", "date_born": "1986-08-05", "place_born": null, "profession": null, "lang": null, "party": "Движение за права и свободи - ДПС", "email": "Bayram.Bayram@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3152", "education": null, "pp": "DPS", "dob": "19860805"},
{"name": "АХМЕД РЕДЖЕБОВ АХМЕДОВ", "date_born": "1974-07-17", "place_born": "Цар Калоян България", "profession": null, "lang": null, "party": "Движение за права и свободи - ДПС", "email": "Ahmed.Ahmedov@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3213", "education": null, "pp": "DPS", "dob": "19740717"},
{"name": "АТАНАС ПЕТРОВ КОСТАДИНОВ", "date_born": "1968-05-03", "place_born": "София България", "profession": null, "lang": null, "party": "БСП за БЪЛГАРИЯ", "email": "Atanas.Kostadinov@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3164", "education": null, "pp": "BSP", "dob": "19680503"},
{"name": "АТАНАС ЗАФИРОВ ЗАФИРОВ", "date_born": "1971-09-29", "place_born": "Бургас България", "profession": null, "lang": null, "party": "БСП за БЪЛГАРИЯ", "email": "Atanas.Zafirov@parliament.bg", "url": "https://www.parliament.bg/bg/MP/2987", "education": null, "pp": "BSP", "dob": "19710929"},
{"name": "ЯВОР РУМЕНОВ БОЖАНКОВ", "date_born": "1990-02-11", "place_born": "Горна Оряховица България", "profession": null, "lang": null, "party": "БСП за БЪЛГАРИЯ", "email": "Yavor.Bozhankov@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3122", "education": null, "pp": "BSP", "dob": "19900211"},
{"name": "ЮМЕР МУСТАФА ХАМЗА", "date_born": "1960-12-04", "place_born": null, "profession": null, "lang": null, "party": "Движение за права и свободи - ДПС", "email": "Yumer.Hamza@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3171", "education": null, "pp": "DPS", "dob": "19601204"},
{"name": "ЦЕЦКА ГЕОРГИЕВА БАЧКОВА", "date_born": "1977-05-11", "place_born": null, "profession": null, "lang": null, "party": "ДЕМОКРАТИЧНА БЪЛГАРИЯ – ОБЕДИНЕНИЕ (ДА България, ДСБ, Зелено движение)", "email": "Tsetska.Bachkova@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3020", "education": null, "pp": "DB", "dob": "19770511"},
{"name": "ЦВЕТАН ИВАНОВ ЕНЧЕВ", "date_born": "1971-10-21", "place_born": null, "profession": null, "lang": null, "party": "Движение за права и свободи - ДПС", "email": "Tsvetan.Enchev@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3042", "education": null, "pp": "DPS", "dob": "19711021"},
{"name": "ХРИСТО ТАНЧЕВ ПРОДАНОВ", "date_born": "1977-03-24", "place_born": "Панагюрище България", "profession": null, "lang": null, "party": "БСП за БЪЛГАРИЯ", "email": "Hristo.Prodanov@parliament.bg", "url": "https://www.parliament.bg/bg/MP/2997", "education": null, "pp": "BSP", "dob": "19770324"},
{"name": "ХРИСТО МИХАЙЛОВ ДОЧЕВ", "date_born": "1980-07-13", "place_born": "Свищов България", "profession": "юрист;преподавател;", "lang": "английски;", "party": "ПП ИМА ТАКЪВ НАРОД", "email": "Hristo.Dochev@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3128", "education": null, "pp": "ITN", "dob": "19800713"},
{"name": "ХРИСТО ЛЮБОМИРОВ ИВАНОВ", "date_born": "1974-09-13", "place_born": null, "profession": null, "lang": null, "party": "ДЕМОКРАТИЧНА БЪЛГАРИЯ – ОБЕДИНЕНИЕ (ДА България, ДСБ, Зелено движение)", "email": "Hristo.Ivanov@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3030", "education": null, "pp": "DB", "dob": "19740913"},
{"name": "ХРИСТО ГЕОРГИЕВ ГАДЖЕВ", "date_born": "1983-05-28", "place_born": "София България", "profession": null, "lang": null, "party": "ГЕРБ-СДС", "email": "Hristo.Gadzhev@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3037", "education": null, "pp": "GERP", "dob": "19830528"},
{"name": "ХРИСТИНА ИВАНОВА ГЕОРГИЕВА", "date_born": "1981-04-19", "place_born": null, "profession": null, "lang": null, "party": "ГЕРБ-СДС", "email": "Hristina.Georgieva@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3233", "education": null, "pp": "GERP", "dob": "19810419"},
{"name": "ХАТИДЖЕ МЕХМЕДОВА ГЕОРГИЕВА", "date_born": "1977-02-20", "place_born": null, "profession": null, "lang": null, "party": "Движение за права и свободи - ДПС", "email": "Hatidzhe.Georgieva@parliament.bg", "url": "https://www.parliament.bg/bg/MP/2989", "education": null, "pp": "DPS", "dob": "19770220"},
{"name": "ХАСАН АХМЕД АДЕМОВ", "date_born": "1953-01-24", "place_born": "Исперих България", "profession": null, "lang": null, "party": "Движение за права и свободи - ДПС", "email": "Hasan.Ademov@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3145", "education": null, "pp": "DPS", "dob": "19530124"},
{"name": "ХАМИД БАРИ ХАМИД", "date_born": "1973-01-05", "place_born": "с. Сини вир България", "profession": null, "lang": null, "party": "Движение за права и свободи - ДПС", "email": "Hamid.Hamid@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3074", "education": null, "pp": "DPS", "dob": "19730105"},
{"name": "ХАЛИЛ РЕДЖЕПОВ ЛЕТИФОВ", "date_born": "1979-04-16", "place_born": "Смолян България", "profession": null, "lang": null, "party": "Движение за права и свободи - ДПС", "email": "Halil.Letifov@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3084", "education": null, "pp": "DPS", "dob": "19790416"},
{"name": "ХАЙРИ РЕДЖЕБОВ САДЪКОВ", "date_born": "1970-12-18", "place_born": "Златарица България", "profession": null, "lang": null, "party": "Движение за права и свободи - ДПС", "email": "Hayri.Sadakov@parliament.bg", "url": "https://www.parliament.bg/bg/MP/2994", "education": null, "pp": "DPS", "dob": "19701218"},
{"name": "ФИЛЧО КРЪСТЕВ ФИЛЕВ", "date_born": "1962-12-18", "place_born": null, "profession": null, "lang": null, "party": "БСП за БЪЛГАРИЯ", "email": "Filcho.Filev@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3108", "education": null, "pp": "BSP", "dob": "19621218"},
{"name": "ФИЛИП СТЕФАНОВ ПОПОВ", "date_born": "1982-01-16", "place_born": "Видин България", "profession": null, "lang": null, "party": "БСП за БЪЛГАРИЯ", "email": "Filip.Popov@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3130", "education": null, "pp": "BSP", "dob": "19820116"},
{"name": "ФИЛИП МАРИНОВ СТАНЕВ", "date_born": "1974-05-07", "place_born": "София България", "profession": "сценарист;", "lang": null, "party": "ПП ИМА ТАКЪВ НАРОД", "email": "Filip.Stanev@parliament.bg", "url": "https://www.parliament.bg/bg/MP/3038", "education": null, "pp": "ITN", "dob": "19740507"},
